plugins {
	id "com.crystaelix.loom" version "1.13-SNAPSHOT"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "com.crystaelix.blossom" version "1.3.2"
	id "me.modmuss50.mod-publish-plugin" version "1.0.0"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.parchmentmc.net/"
			}
		}
		filter {
			includeGroup "org.parchmentmc.data"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.nucleoid.xyz/"
			}
		}
		filter {
			includeGroup "eu.pb4"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.terraformersmc.com/"
			}
		}
		filter {
			includeGroup "com.terraformersmc"
			includeGroup "com.terraformersmc.terraform-api"
			includeGroup "dev.emi"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "mezz.jei"
			includeGroup "vazkii.patchouli"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.crystaelix.com/releases/"
			}
		}
		filter {
			includeGroup "thelm.jeidrawables"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.ladysnake.org/releases/"
			}
		}
		filter {
			includeGroup "dev.onyxstudios.cardinal-components-api"
			includeGroup "org.ladysnake"
			includeGroup "io.github.ladysnake"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.jamieswhiteshirt.com/libs-release/"
			}
		}
		filter {
			includeGroup "com.jamieswhiteshirt"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://jitpack.io/"
			}
		}
		filter {
			includeGroup "com.github.emilyploszaj"
			includeGroup "com.github.Virtuoel"
		}
	}
}

def mcVersion = "1.20.1"
def modName = "BewitchmentJEI"
def modId = "bewitchmentjei"
def specVersion = "20.1"
def vendor = "thelm"

group = "thelm.bewitchmentjei"
version = "20.1.0"

def archivesName = modName
base.archivesName = archivesName

sourceSets {
	main
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	mixin.defaultRefmapName = "${modId}.refmap.json"
	runs {
		configureEach {
			property "fabric.log.console.level", "debug"
		}
		client {
			programArg "--username=Dev"
		}
		server
	}
}

dependencies {
	// Minecraft
	minecraft "com.mojang:minecraft:1.20.1"
	mappings loom.layered {
		mappings "net.fabricmc:yarn:1.20.1+build.10:v2"
		parchment "org.parchmentmc.data:parchment-1.20.1:2023.09.03@zip"
	}
	modImplementation "net.fabricmc:fabric-loader:0.17.2"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.6+1.20.1"
	modImplementation "eu.pb4:placeholder-api:2.1.4+1.20.1"
	modImplementation "com.terraformersmc:modmenu:7.2.2"

	// JEI
	modImplementation("mezz.jei:jei-1.20.1-fabric:15.20.0.116") {transitive = false}
	include(modImplementation("thelm.jeidrawables:JEIDrawables-Fabric:20.1.4"))

	// Bewitchment External Dependencies
	implementation "me.zeroeightsix:fiber:0.23.0-2"
	modImplementation "vazkii.patchouli:Patchouli:1.20.1-84.1-FABRIC"
	modImplementation("com.github.Virtuoel:Pehkui:3.8.0") {exclude group: "net.fabricmc.fabric-api"}
	modImplementation "dev.emi:trinkets:3.7.2"

	// Bewitchment Included Dependencies
	modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-api:5.2.3"
	modImplementation("me.lucko:fabric-permissions-api:0.3.3") {exclude group: "net.fabricmc.fabric-api"}
	modImplementation("org.ladysnake:impersonate:2.10.3") {exclude group: "net.fabricmc.fabric-api"}
	modImplementation "io.github.ladysnake:PlayerAbilityLib:1.8.0"
	modImplementation "curse.maven:midnightlib-488090:4576371"
	modImplementation "com.jamieswhiteshirt:reach-entity-attributes:2.4.0"
	modImplementation "com.github.emilyploszaj:step-height-entity-attribute:1.2.0"
	modImplementation "com.terraformersmc.terraform-api:terraform-wood-api-v1:7.0.3"

	// Bewitchment
	modImplementation "curse.maven:bewitchment-394915:5819540"
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesName
			artifact remapJar
			artifact remapSourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = project.version
	changelog = file("changelog.md").text
	type = STABLE
	modLoaders.add("fabric")
	additionalFiles.from(remapSourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "1324144"
		minecraftVersions.add(mcVersion)
		requires "jei", "bewitchment"
		incompatible "emi"
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "crCTnaxN"
		minecraftVersions.add(mcVersion)
		requires "jei", "bewitchment"
		incompatible "emi"
	}
}
