modLoader = "lowcodefml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/BewitchmentJEI/issues"

[properties]
	"connector:placeholder" = true

[[mods]]
	modId = "bewitchmentjei"
	version = "0@VERSION@"
	displayName = "BewitchmentJEI"
	description = "An addon to Bewitchment that adds JEI support."
	logoFile = "bewitchmentjei.logo.png"
	authors = "TheLMiffy1111"

[[dependencies.bewitchmentjei]]
	modId = "minecraft"
	versionRange = "[1.20,1.20.2)"
	mandatory = true

[[dependencies.bewitchmentjei]]
	modId = "connector"
	versionRange = "*"
	mandatory = true

[[dependencies.bewitchmentjei]]
	modId = "connectorextras"
	versionRange = "*"
	mandatory = true

[[dependencies.bewitchmentjei]]
	modId = "jei"
	versionRange = "*"
	mandatory = true

[[dependencies.bewitchmentjei]]
	modId = "jeidrawables"
	versionRange = "*"
	mandatory = true

[[dependencies.bewitchmentjei]]
	modId = "bewitchment"
	versionRange = "*"
	mandatory = true
